version: 2
updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directories:
      - /*/
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: daily
