version: 2
updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    directories:
      - /
      - /*/
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: daily
  - package-ecosystem: pre-commit
    cooldown:
      default-days: 7
    directory: /
    groups:
      pre-commit:
        patterns:
          - "*"
    schedule:
      interval: daily
  - package-ecosystem: uv
    allow:
      - dependency-type: all
    cooldown:
      default-days: 7
    directory: /
    schedule:
      interval: daily
