name: Set up pre-commit
description: >
  Caches and sets up environments for pre-commit.
  Requires uv to be set up first, e.g. by using ./set-up-uv.
  Requires pre-commit to be specified as a (dev) dependency in pyproject.toml.
  Requires a .pre-commit-config.yaml file in the repository.
inputs:
  cache-key-suffix:
    default: ""
    description: Key suffix for the pre-commit cache. Useful for differentiating between runs
  install-git-hooks:
    default: "false"
    description: Whether to install the git hooks for pre-commit
runs:
  using: composite
  steps:
    - id: cache
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        key: pre-commit--${{ hashFiles('.pre-commit-config.yaml') }}-${{ inputs.cache-key-suffix }}
        path: ~/.cache/pre-commit
    - if: steps.cache.outputs.cache-hit != 'true'
      run: uv run --no-sync pre-commit install-hooks # sets up the pre-commit environments
      shell: bash
    - if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        key: pre-commit--${{ hashFiles('.pre-commit-config.yaml') }}-${{ inputs.cache-key-suffix }}
        path: ~/.cache/pre-commit
    - if: fromJSON(inputs.install-git-hooks)
      run: uv run --no-sync pre-commit install # sets up the git hooks for pre-commit
      shell: bash
