name: Set up pre-commit
description: >
  Caches and sets up environments for pre-commit.
  Requires uv to be set up first, e.g. by using ./set-up-uv.
inputs:
  cache-key-suffix:
    default: ""
    description: Key suffix for the pre-commit cache. Useful for differentiating runs
  install-git-hooks:
    default: "false"
    description: Whether to install the git hooks for pre-commit
runs:
  using: composite
  steps:
    - id: cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
      with:
        key: pre-commit--${{ hashFiles('.pre-commit-config.yaml') }}-${{ inputs.cache-key-suffix }}
        path: ~/.cache/pre-commit
    - if: steps.cache.outputs.cache-hit != 'true'
      run: uv run --no-sync pre-commit install-hooks # sets up the pre-commit environments
      shell: bash
    - if: fromJSON(inputs.install-git-hooks)
      run: uv run --no-sync pre-commit install # sets up the git hooks for pre-commit
      shell: bash
