name: Set up pre-commit
description: Cache and set up environments for pre-commit
inputs:
  cache-key-suffix:
    default: ""
    description: Key suffix for the pre-commit cache. Useful for differentiating runs.
    required: true
  install-git-hooks:
    default: "false"
    description: whether to install the git hooks for pre-commit
    required: true
runs:
  using: composite
  steps:
    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
      with:
        key: pre-commit--${{ hashFiles('.pre-commit-config.yaml') }}-${{ inputs.cache-key-suffix }}
        path: ~/.cache/pre-commit
    - run: uv run --no-sync pre-commit install-hooks # sets up the pre-commit environments
      shell: bash
    - if: fromJSON(inputs.install-git-hooks)
      run: uv run --no-sync pre-commit install # sets up the git hooks for pre-commit
      shell: bash
